spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sss?serverTimezone=UTC
    username: root
    password: pure6671
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: trace

auth:
  access: asdwqedsaasdwqesadsjosjndknaskmlcnkejdoknlksamlcnsqlkndoqkwacsdqwa
  refresh: wqeniodnvsksadowqjndlknmsandokwqmlkdnjnfcosajkjqkwdmklsankclnwondkwqnldsneqdsndk

server:
  get:
    url: 10.80.163.15:8080
  port: 8000
